CREATE TABLE quotation_requests (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    client_id BIGINT NOT NULL,
    policy_type VARCHAR(60) NULL,
    status ENUM(
        'EMAIL_RECEIVED','PROCESSING','DATA_EXTRACTED','VALIDATING',
        'MISSING_INFORMATION','WAITING_FOR_CLIENT','CLIENT_REPLY_RECEIVED',
        'RE_VALIDATING','READY_FOR_QUOTATION','QUOTATION_GENERATED',
        'QUOTATION_SENT','COMPLETED',
        'EMAIL_PROCESSING_FAILED','DATA_EXTRACTION_FAILED',
        'QUOTATION_GENERATION_FAILED','EMAIL_SEND_FAILED',
        'MANUAL_REVIEW_REQUIRED'
    ) NOT NULL DEFAULT 'EMAIL_RECEIVED',
    assigned_to BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_qr_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_qr_assigned FOREIGN KEY (assigned_to) REFERENCES users(id),
    INDEX idx_qr_status (status),
    INDEX idx_qr_created_at (created_at)
);