ALTER TABLE incoming_emails
    ADD COLUMN in_reply_to VARCHAR(255) NULL,
    ADD COLUMN sender_email VARCHAR(150) NOT NULL,
    ADD COLUMN subject VARCHAR(255) NULL,
    ADD COLUMN body TEXT NULL,
    ADD COLUMN processing_status ENUM('RECEIVED','PROCESSED','FAILED') NOT NULL DEFAULT 'RECEIVED',
    ADD COLUMN received_at TIMESTAMP NOT NULL,
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;